require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PromotionalRulesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PromotionalRule. As you add validations to PromotionalRule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PromotionalRulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all promotional_rules as @promotional_rules" do
      promotional_rule = PromotionalRule.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:promotional_rules)).to eq([promotional_rule])
    end
  end

  describe "GET show" do
    it "assigns the requested promotional_rule as @promotional_rule" do
      promotional_rule = PromotionalRule.create! valid_attributes
      get :show, {:id => promotional_rule.to_param}, valid_session
      expect(assigns(:promotional_rule)).to eq(promotional_rule)
    end
  end

  describe "GET new" do
    it "assigns a new promotional_rule as @promotional_rule" do
      get :new, {}, valid_session
      expect(assigns(:promotional_rule)).to be_a_new(PromotionalRule)
    end
  end

  describe "GET edit" do
    it "assigns the requested promotional_rule as @promotional_rule" do
      promotional_rule = PromotionalRule.create! valid_attributes
      get :edit, {:id => promotional_rule.to_param}, valid_session
      expect(assigns(:promotional_rule)).to eq(promotional_rule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PromotionalRule" do
        expect {
          post :create, {:promotional_rule => valid_attributes}, valid_session
        }.to change(PromotionalRule, :count).by(1)
      end

      it "assigns a newly created promotional_rule as @promotional_rule" do
        post :create, {:promotional_rule => valid_attributes}, valid_session
        expect(assigns(:promotional_rule)).to be_a(PromotionalRule)
        expect(assigns(:promotional_rule)).to be_persisted
      end

      it "redirects to the created promotional_rule" do
        post :create, {:promotional_rule => valid_attributes}, valid_session
        expect(response).to redirect_to(PromotionalRule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved promotional_rule as @promotional_rule" do
        post :create, {:promotional_rule => invalid_attributes}, valid_session
        expect(assigns(:promotional_rule)).to be_a_new(PromotionalRule)
      end

      it "re-renders the 'new' template" do
        post :create, {:promotional_rule => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested promotional_rule" do
        promotional_rule = PromotionalRule.create! valid_attributes
        put :update, {:id => promotional_rule.to_param, :promotional_rule => new_attributes}, valid_session
        promotional_rule.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested promotional_rule as @promotional_rule" do
        promotional_rule = PromotionalRule.create! valid_attributes
        put :update, {:id => promotional_rule.to_param, :promotional_rule => valid_attributes}, valid_session
        expect(assigns(:promotional_rule)).to eq(promotional_rule)
      end

      it "redirects to the promotional_rule" do
        promotional_rule = PromotionalRule.create! valid_attributes
        put :update, {:id => promotional_rule.to_param, :promotional_rule => valid_attributes}, valid_session
        expect(response).to redirect_to(promotional_rule)
      end
    end

    describe "with invalid params" do
      it "assigns the promotional_rule as @promotional_rule" do
        promotional_rule = PromotionalRule.create! valid_attributes
        put :update, {:id => promotional_rule.to_param, :promotional_rule => invalid_attributes}, valid_session
        expect(assigns(:promotional_rule)).to eq(promotional_rule)
      end

      it "re-renders the 'edit' template" do
        promotional_rule = PromotionalRule.create! valid_attributes
        put :update, {:id => promotional_rule.to_param, :promotional_rule => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested promotional_rule" do
      promotional_rule = PromotionalRule.create! valid_attributes
      expect {
        delete :destroy, {:id => promotional_rule.to_param}, valid_session
      }.to change(PromotionalRule, :count).by(-1)
    end

    it "redirects to the promotional_rules list" do
      promotional_rule = PromotionalRule.create! valid_attributes
      delete :destroy, {:id => promotional_rule.to_param}, valid_session
      expect(response).to redirect_to(promotional_rules_url)
    end
  end

end
